
import { useState } from 'react';
import { ArrowUpRight, CheckCircle2, Container, Package, Scale, Target, TrendingUp, Warehouse } from 'lucide-react';
import { Link } from 'react-router';
import { addMonths, format, parseISO } from 'date-fns';
import { Bar, BarChart, CartesianGrid, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import ContainerIcon from '@/components/ContainerIcon';
import { useApp } from '@/context/AppContext';
import { CONFIG, HOY, armarContenedores, calcularAvanceAnual, calcularMetaMensual, calcularProduccionAdicional, contenedoresDelMes, formatFecha, formatLb, labelMes, lotesPorMesSalida, mesesConDatos, type ProduccionLote } from '@/services/dataService';

export function Progress({ value, label }: { value: number; label: string }) {
  return <div className="exec-progress" role="progressbar" aria-label={label} aria-valuenow={Math.min(100, value)} aria-valuemin={0} aria-valuemax={100}><span style={{ width: `${Math.min(100, Math.max(0, value))}%` }} /></div>;
}
export function MonthSelector() {
  const { mesReferencia, setMesReferencia } = useApp();
  const move = (n: number) => setMesReferencia(format(addMonths(parseISO(`${mesReferencia}-01`), n), 'yyyy-MM'));
  return <div className="exec-month"><button onClick={() => move(-1)} aria-label="Mes anterior">‹</button><input aria-label="Mes de planificación" type="month" value={mesReferencia} onChange={e => e.target.value && setMesReferencia(e.target.value)} /><button onClick={() => move(1)} aria-label="Mes siguiente">›</button></div>;
}
export function MonthlyKpis({ lotes, mes }: { lotes: ProduccionLote[]; mes: string }) {
  const r = contenedoresDelMes(lotes, mes);
  const cards = [
    { label: 'Producción proyectada', value: formatLb(r.pesoTotal), note: 'Peso final · merma del 10% aplicada', icon: Scale },
    { label: 'Contenedores completos', value: `${r.completos} de ${CONFIG.metaContenedoresMes}`, note: `Capacidad de ${formatLb(CONFIG.capacidadContenedorLb)}`, icon: Container },
    { label: 'Contenedor en proceso', value: formatLb(r.parcialLb), note: `de ${formatLb(CONFIG.capacidadContenedorLb)} · faltan ${formatLb(CONFIG.capacidadContenedorLb - r.parcialLb)}`, icon: Package },
    { label: 'Faltante para meta mensual', value: formatLb(r.faltanteParaMetaLb), note: `Meta: ${formatLb(calcularMetaMensual())}`, icon: Target },
    { label: 'Cumplimiento del mes', value: `${r.avancePct.toFixed(1)}%`, note: r.faltanteParaMetaLb ? 'Avanzando hacia la meta mensual' : 'Meta mensual cumplida', icon: TrendingUp },
    { label: 'Producciones disponibles', value: `${lotesPorMesSalida(lotes, mes).length} IDs`, note: 'Según fecha de salida del mes', icon: Warehouse },
  ];
  return <div className="exec-kpis">{cards.map(({ label, value, note, icon: Icon }, i) => <article className={`exec-card exec-kpi ${i === 0 ? 'primary-kpi' : ''}`} key={label}><div className="exec-row"><p className="exec-label">{label}</p><Icon size={19} /></div><strong>{value}</strong><p>{note}</p>{i === 4 && <Progress value={r.avancePct} label={label} />}</article>)}</div>;
}
export function ContainerSection({ lotes, mes }: { lotes: ProduccionLote[]; mes: string }) {
  const [selected, setSelected] = useState<number | null>(null);
  const plans = armarContenedores(lotes, mes);
  const slots = Array.from({ length: Math.max(CONFIG.metaContenedoresMes, plans.length) }, (_, i) => plans[i] ?? { numero: i + 1, mes, peso: 0, faltante: CONFIG.capacidadContenedorLb, porcentaje: 0, completo: false, asignaciones: [], cantidadIds: 0, bultos: 0 });
  const c = slots.find(c => c.numero === selected);
  return <section className="exec-section"><div className="exec-section-title"><div><h2>Plan de contenedores</h2><p>{labelMes(mes)} · asignación por fecha de salida</p></div><span className="exec-pill">Meta mensual · {CONFIG.metaContenedoresMes} contenedores</span></div><div className="exec-containers">{slots.map(c => <button className={`exec-card container-card ${c.completo ? 'is-complete' : ''}`} key={c.numero} onClick={() => setSelected(c.numero)}><div className="exec-row"><h3>Contenedor {c.numero}</h3><ArrowUpRight size={17} /></div><div className="container-art"><ContainerIcon height={76} variant={c.completo ? 'full' : c.peso ? 'half' : 'outline'} fillPct={c.porcentaje} /><span className="exec-pill">{c.completo ? '✓ Completo' : c.peso ? 'En proceso' : 'Pendiente'}</span></div><div className="exec-row"><strong>{formatLb(c.peso)}</strong><b>{c.porcentaje.toFixed(1)}%</b></div><p>de {formatLb(CONFIG.capacidadContenedorLb)}</p><Progress value={c.porcentaje} label={`Contenedor ${c.numero}`} /><p className="container-note">{c.completo ? `${c.cantidadIds} IDs de producción asignados` : `Faltan ${formatLb(c.faltante)}`}</p><span className="exec-link">Ver composición →</span></button>)}</div><p className="exec-footnote">Cada mes se planifica por separado. Los excedentes permanecen en su mes de salida; el peso de un ID puede dividirse entre contenedores.</p>
    <Dialog open={!!c} onOpenChange={open => !open && setSelected(null)}><DialogContent className="exec-dialog sm:max-w-4xl"><DialogHeader><DialogTitle>Contenedor {c?.numero} · {labelMes(mes)}</DialogTitle><DialogDescription>Composición proyectada en orden de fecha de salida.</DialogDescription></DialogHeader>{c && <><div className="exec-detail-stats">{[['Capacidad', formatLb(CONFIG.capacidadContenedorLb)], ['Peso acumulado', formatLb(c.peso)], ['Peso faltante', formatLb(c.faltante)], ['Porcentaje', `${c.porcentaje.toFixed(1)}%`], ['Cantidad de IDs', c.cantidadIds], ['Bultos equivalentes', c.bultos.toFixed(2)]].map(([label, value]) => <div key={label}><p>{label}</p><strong>{value}</strong></div>)}</div><Progress value={c.porcentaje} label="Llenado del contenedor" /><div className="exec-table-wrap"><table className="exec-table"><thead><tr>{['ID Producción', 'Fecha Salida', 'Bultos del ID', 'Peso final proyectado', 'Peso asignado'].map(t => <th key={t}>{t}</th>)}</tr></thead><tbody>{c.asignaciones.map(a => <tr key={a.lote.no}><td><strong>{a.lote.idProduccion}</strong>{a.pesoAsignado < a.lote.pesoFinalProyLb && <small>ID compartido entre contenedores</small>}</td><td>{formatFecha(a.lote.fechaSalida, 'dd/MM/yyyy')}</td><td>{a.lote.bultos}</td><td>{formatLb(a.lote.pesoFinalProyLb)}</td><td><strong>{formatLb(a.pesoAsignado)}</strong></td></tr>)}</tbody></table>{!c.asignaciones.length && <p className="p-6">Todavía no hay producciones asignadas.</p>}</div><p className="exec-footnote">Los bultos equivalentes se prorratean por peso; no representan un fraccionamiento físico. La tabla muestra los bultos originales del ID.</p></>}</DialogContent></Dialog>
  </section>;
}
export function MonthlyOutlook({ lotes, mes }: { lotes: ProduccionLote[]; mes: string }) {
  const { setMesReferencia } = useApp();
  const data = Array.from({ length: 4 }, (_, i) => { const m = format(addMonths(parseISO(`${mes}-01`), i), 'yyyy-MM'); return { mes: m, label: labelMes(m), ...contenedoresDelMes(lotes, m) }; });
  return <section className="exec-section"><div className="exec-section-title"><div><h2>Proyección de contenedores</h2><p>Disponibilidad futura según fecha de salida</p></div><Link to="/proyeccion" className="exec-link">Explorar proyección →</Link></div><div className="exec-outlook">{data.map(r => <button key={r.mes} className="exec-card month-card" onClick={() => setMesReferencia(r.mes)}><h3>{r.label}</h3><strong>{formatLb(r.pesoTotal)}</strong><p>{r.totalConParcial.toFixed(2)} contenedores · meta {CONFIG.metaContenedoresMes}</p><Progress value={r.avancePct} label={r.label} /><div className="exec-row"><b>{r.avancePct.toFixed(1)}%</b><span className={`exec-pill ${r.faltanteParaMetaLb ? 'pending' : ''}`}>{r.faltanteParaMetaLb ? 'Producción pendiente' : 'Meta cumplida'}</span></div><p>Faltante: {formatLb(r.faltanteParaMetaLb)}</p></button>)}</div><div className="exec-card exec-chart"><div className="exec-row"><h3>Producción proyectada vs. meta mensual</h3><span className="exec-muted">Meta: {formatLb(calcularMetaMensual())}</span></div><div style={{ height: 250, width: '100%', minWidth: 0 }}><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{ top: 25, right: 20, left: 5, bottom: 5 }}><CartesianGrid vertical={false} stroke="#e6ebe8" /><XAxis dataKey="label" tick={{ fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis tickFormatter={n => `${n / 1000}k`} tick={{ fontSize: 11 }} axisLine={false} tickLine={false} domain={[0, 'auto']} /><Tooltip formatter={v => formatLb(Number(v))} /><ReferenceLine y={calcularMetaMensual()} stroke="#bc8b38" strokeDasharray="5 5" ifOverflow="extendDomain" /><Bar name="Peso final proyectado" dataKey="pesoTotal" fill="#247968" radius={[5, 5, 0, 0]} maxBarSize={62} /></BarChart></ResponsiveContainer></div></div></section>;
}
export function AnnualProgress({ lotes, anio }: { lotes: ProduccionLote[]; anio: string }) {
  const a = calcularAvanceAnual(lotes, anio);
  return <section className="exec-card annual-card"><div className="exec-section-title"><div><p className="exec-label">Perspectiva anual · {anio}</p><h2>Un año de producción, una meta compartida.</h2></div><Target size={30} /></div><div className="annual-stats">{[['Meta anual', a.meta], ['Contenedores proyectados', a.proyectados.toFixed(2)], ['Contenedores completos', a.completos], ['Contenedores pendientes', a.pendientes], ['Cumplimiento anual', `${a.porcentaje.toFixed(1)}%`]].map(([label, value]) => <div key={label}><strong>{value}</strong><p>{label}</p></div>)}</div><Progress value={a.porcentaje} label="Avance anual" /><p className="exec-footnote">Completos: suma de contenedores llenos de cada mes. Proyectados: equivalente del peso anual, incluidos parciales. Pendientes: meta menos completos.</p></section>;
}
export function MaturationSection({ lotes, showIds = false }: { lotes: ProduccionLote[]; showIds?: boolean }) {
  const filas = lotes.filter(l => !l.empacado).sort((a, b) => a.fechaSalida.localeCompare(b.fechaSalida));
  const proxima = filas.find(l => l.fechaSalida >= format(HOY, 'yyyy-MM-dd'));
  return <section className="exec-card maturation-card"><div className="exec-section-title"><div><p className="exec-label">Disponibilidad futura</p><h2>Producto en Maduración</h2></div><Warehouse size={26} /></div><div className="exec-detail-stats"><div><p>Peso proyectado disponible</p><strong>{formatLb(filas.reduce((s, l) => s + l.pesoFinalProyLb, 0))}</strong></div><div><p>Producciones</p><strong>{filas.length} IDs</strong></div><div><p>Bultos</p><strong>{filas.reduce((s, l) => s + l.bultos, 0)}</strong></div><div><p>Próxima salida</p><strong>{proxima ? formatFecha(proxima.fechaSalida, 'dd/MM/yyyy') : 'Sin salidas futuras'}</strong></div></div><div className="maturation-months">{mesesConDatos(filas).map(m => <div className="exec-row" key={m}><span>{labelMes(m)}</span><strong>{formatLb(contenedoresDelMes(filas, m).pesoTotal)}</strong></div>)}</div>{showIds && <div className="exec-table-wrap max-h-96 mb-5"><table className="exec-table"><thead><tr><th>ID Producción</th><th>Fecha Salida</th><th>Bultos</th><th>Peso proyectado</th><th>Estado</th></tr></thead><tbody>{filas.map(l => <tr key={l.no}><td><Link className="exec-link" to={`/produccion?q=${l.idProduccion}`}>{l.idProduccion}</Link></td><td>{formatFecha(l.fechaSalida, 'dd/MM/yyyy')}</td><td>{l.bultos}</td><td>{formatLb(l.pesoFinalProyLb)}</td><td>{l.estado}</td></tr>)}</tbody></table></div>}<Link className="exec-link" to="/produccion?empacado=false">Consultar todos los IDs no empacados →</Link><p className="exec-footnote">Este producto ya está incluido en la proyección mensual; no se suma nuevamente.</p></section>;
}
export function ManagementMessage({ lotes, mes }: { lotes: ProduccionLote[]; mes: string }) {
  const r = contenedoresDelMes(lotes, mes);
  return <div className="management-message"><CheckCircle2 size={24} /><div><p className="exec-label">Indicador para Gerencia</p><strong>{labelMes(mes)}: {r.faltanteParaMetaLb ? `producción proyectada para ${r.totalConParcial.toFixed(2)} contenedores. Faltan ${formatLb(r.faltanteParaMetaLb)} para cumplir la meta mensual.` : `meta mensual cumplida. Producción proyectada para ${r.totalConParcial.toFixed(2)} contenedores.`}</strong></div></div>;
}
export function ProductionGap({ lotes, mes }: { lotes: ProduccionLote[]; mes: string }) {
  const r = contenedoresDelMes(lotes, mes);
  return <section className="exec-card gap-card"><p className="exec-label">Plan de acción · {labelMes(mes)}</p><h2>¿Cuánto falta producir?</h2><dl>{[['Meta mensual', formatLb(calcularMetaMensual())], ['Producción proyectada', formatLb(r.pesoTotal)], ['Pendiente en peso final', formatLb(r.faltanteParaMetaLb)], ['Equivalente en contenedores', (r.faltanteParaMetaLb / CONFIG.capacidadContenedorLb).toFixed(2)]].map(([k, v]) => <div className="exec-row" key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="gap-highlight"><p>Peso inicial adicional a producir</p><strong>{formatLb(calcularProduccionAdicional(r.faltanteParaMetaLb))}</strong><p>Considera la merma estimada del 10%.</p></div></section>;
}
